image:
  repository: daxgrid/job-topology-api
  tag: v0.4.1

imgPullSecret: regcred

resources:
  memoryRequest: 100Mi
  memoryLimit: 125Mi

port: 80
serviceType: ClusterIP

appsettings:
  settings:
    blobstorageConnectionString: ""
