image:
  repository: openftth/danish-address-seed
  tag: v2.0.1

schedule: "0 0 * * *"

restartPolicy: Never
backoffLimit: 0

requests:
  memoryRequest: "150Mi"
  memoryLimit: "300Mi"

connectionString: ""

typesense:
  host: ""
  port: 80
  protocol: http
  apiKey: ""
