image:
  repository: openftth/specification-importer
  tag: v0.9.0

resources:
  memoryRequest: 150Mi
  memoryLimit: 175Mi

executeScript: null

appsettings:
  settings:
    specificationFilesRootPath: "/specifications"
    clientId: ""
    clientSecret: ""
    tokenEndpoint: ""
    graphQlAddress: ""
