image:
  repository: typesense/typesense
  tag: 0.25.1

replicas: 1
port: 80
serviceType: NodePort

apiKey: changeme!

resources:
  memoryRequest: "125Mi"
  memoryLimit: "150Mi"

storage:
  className: ""
  size: 4Gi
  path: /data
