loglevel: "Information"

image:
  repository: openftth/route-network-search-indexer
  tag: v4.0.0

eventStore:
  connectionString: ""

typesense:
  host: openftth-search-typesense
  port: 80
  protocol: http
  apiKey: ""
