image:
  repository: openftth/address-change-indexer
  tag: v0.5.4

resources:
  memoryRequest: 2.75Gi
  memoryLimit: 3.0Gi

appsettings:
  settings:
    eventStoreConnectionString: ""
    geoDatabaseConnectionString: ""
