image:
  repository: openftth/nord-energi-open-net
  tag: v0.3.3

resources:
  memoryRequest: "200Mi"
  memoryLimit: "250Mi"

service:
  externalPort: 80
  type: ClusterIP

appsettings:
  settings:
    connectionString: ""
