serviceType: ClusterIP
serviceAnnotations: {}

replicas: 1

resources:
  memoryRequest: 750Mi
  memoryLimit: 1000Mi

image:
  repository: keycloak/keycloak
  tag: 26.5.0

healthEnabled: "true"

username: ""
password: ""

hostname: ""
hostnameStrict: "false"

database:
  type: postgres
  connectionstring: ""
  username: ""
  password: ""
