image:
  repository: openftth/aura-circuit-integration
  tag: v1.0.1

resources:
  memoryRequest: "175Mi"
  memoryLimit: "200Mi"

appsettings:
  settings:
    serviceBus:
      readConnectionString: ""
      sendConnectionString: ""
      headerTypeName: ""
      readTopicName: ""
      readSubscriptionName: ""
      sendTopicName: ""
    database:
      host: ""
      port: ""
      database: ""
      username: ""
      password: ""
    graphQL:
      clientId: ""
      clientSecret: ""
      endPoint: ""
      tokenEndPoint: ""
