image:
  repository: openftth/nord-energi-installation-address-creator
  tag: v0.3.9

resources:
  memoryRequest: 1.25Gi
  memoryLimit: 1.5Gi

appsettings:
  settings:
    eventStoreConnectionString: ""
    geoDatabaseConnectionString: ""
    supplyZonePolygonTableName: ""
    installationAddressTableName: ""
