image:
  repository: openftth/aura-address-integrator
  tag: v0.1.2

resources:
  memoryRequest: "250Mi"
  memoryLimit: "300Mi"

appsettings:
  settings:
    eventStoreConnectionString: ""
    serviceBusConnectionString: ""
    serviceBusTopicName: ""
    serviceBusSubscriptionName: ""
    serviceBusHeaderTypeName: ""
