image:
  repository: openftth/aura-address-integrator
  tag: v0.5.1

resources:
  memoryRequest: "750Mi"
  memoryLimit: "850Mi"

appsettings:
  settings:
    eventStoreConnectionString: ""
    serviceBusConnectionString: ""
    serviceBusTopicName: ""
    serviceBusSubscriptionName: ""
    serviceBusHeaderTypeName: ""
