image:
  repository: openftth/aura-address-integrator
  tag: v0.1.6

resources:
  memoryRequest: "500Mi"
  memoryLimit: "550Mi"

appsettings:
  settings:
    eventStoreConnectionString: ""
    serviceBusConnectionString: ""
    serviceBusTopicName: ""
    serviceBusSubscriptionName: ""
    serviceBusHeaderTypeName: ""
