replicas: 1
serviceType: NodePort

image:
  repository: openftth/frontend
  tag: v8.3.5

desktopBridgeUri: ""
apiGatewayHttpUri: ""
apiGatewayWsUri: ""
keyCloakUri: ""

routeNetworkTileServerUri: ""
aerialPhotoServerUri: ""
basemapTileServerUri: ""

colorMarkings:
  - Blue
  - Red
  - Green

layers: {}

informationControlConfig: {}

maplibreJson: ""

defaultUserLanguage: "en"

initialUserPrompt: {}
