replicas: 1
serviceType: NodePort

image:
  repository: openftth/frontend
  tag: v5.78.0

desktopBridgeUri: ""
apiGatewayHttpUri: ""
apiGatewayWsUri: ""
keyCloakUri: ""

routeNetworkTileServerUri: ""
aerialPhotoServerUri: ""
basemapTileServerUri: ""

colorMarkings:
  - Blue
  - Red
  - Green

layers: {}

informationControlConfig: {}

maplibreJson: ""
