loglevel: "Information"

image:
  repository: openftth/equipment-search-indexer
  tag: v1.3.0

resources:
  memoryRequest: "1Gi"
  memoryLimit: "1.25Gi"

connectionstring: ""

specifications:
  - ""

typesense:
  host: openftth-search-typesense
  port: 80
  protocol: http
  apiKey: ""
  collectionAlias: equipments
