loglevel: "Information"

image:
  repository: openftth/relational-projector
  tag: v1.0.0
  
eventStoreDatabase:
  name: EVENT_STORE
  username: postgres
  password: postgres

geoDatabase:
  name: OPEN_FTTH
  username: postgres
  password: postgres