loglevel: "Information"

image:
  repository: openftth/relational-projector
  tag: v1.19.0
  
resources:
  memoryRequest: "512Mi"
  memoryLimit: "768Mi"

eventStoreDatabase:
  host: openftth-event-store-postgresql
  name: EVENT_STORE
  username: postgres
  password: postgres

geoDatabase:
  host: openftth-postgis
  name: OPEN_FTTH
  username: postgres
  password: postgres
