loglevel: "Information"

image:
  repository: openftth/relational-projector
  tag: v1.4.0
  
resources:
  memoryRequest: "512Mi"
  memoryLimit: "768Mi"

eventStoreDatabase:
  name: EVENT_STORE
  username: postgres
  password: postgres

geoDatabase:
  name: OPEN_FTTH
  username: postgres
  password: postgres
