image:
  repository: openftth/address-import-dawa
  tag: v0.3.0

schedule: "0 0 * * *"
restartPolicy: Never
backoffLimit: 0

resources:
  memoryRequest: 2Gi
  memoryLimit: 2.25Gi

appsettings:
  settings:
    eventStoreConnectionString: ""
