image:
  repository: daxgrid/cimflow-job-overview
  tag: v0.7.0

replicas: 1

port: 80
serviceType: ClusterIP

resources:
  memoryRequest: 100Mi
  memoryLimit: 125Mi

customerName: customer-name
username: username
password: password
